### ISSUE TITLE
Tarantool Profiles vs GlobalProfiles

### ISSUE THREAD

**Issue by pjao** [BrandMeister/bm-pos2aprs#1]
Hi!

Profiles doesn't exists on newer versions, it was replaced with GlobalProfiles.

Please check.

**Comment by nonoo** [comment]
I'm running the latest BM (20170810-074109) and there is no GlobalProfiles space, only Profiles.

**Comment by pjao** [comment]
This is not BM related, but Tarantools/Registry and Replicator. Some how, you still have the old way working.

brandmeister -> 20170810-074109
brandmeister-registry-ng -> 20170811-160430
tarantool-mysql-replicator -> 20170528-113618

After the change it's also needed to shift fields one position plus.

Maybe one parameter to allow working with new and old version?
