### ISSUE TITLE
From APRS to BM (DMR)

### ISSUE THREAD

**Issue by pablitonadal** [BrandMeister/bm-pos2aprs#5]
Hi, thanks for your help but sorry, I can't find anyone to help me solve the problem.

I'am Italian ham radio (IZ3QTC 2223693), my name's Paolo.

I'm see this guide at link

https://bm.pd0zry.nl/index.php/APRS.

For part "form DMR to APRS", there aren't a problem.
I send the message at address 222999 and I see the message at APRS NETWORK.
But for part "from APRS to DMR" I send message but I don't receive the message on my radio.

Do you have some suggestion?

My packet test it was this:

:IZ3QTC-3 :Test 1
IZ3QTC-6>APBM1S::IZ3QTC-3 : TEST APBM1S
IZ3QTC-6>APBM::IZ3QTC-3 : TEST APBM
IZ3QTC-6>APBMXX::IZ3QTC-3 : TEST APBMXX
IZ3QTC-6>APBM1D::IZ3QTC-3 : TEST APBM1D

(My radio is TYT MD2017 and RETEVIS HD1)

73, by IZ3QTC Paolo.

**Comment by nonoo** [comment]
Your issue is not related to bm-pos2aprs. Please ask support at https://ask.brandmeister.network/
